typography_spectrum: 0.580908338772133
color:
  saturation: 0.6565779247321188
  brandStrength: 0.6287015543784946
  rhythmicContrast: 0.08832667651586235
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
  lightness: 0.44851268199272454
layout_spectrum: 0.47758101182989776
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8f9f2c37-6361-4b15-9bb7-52b5d45902f6.png
name: fivecloves
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/45c9fde1-3a11-48a4-bb54-8c211e7390d4.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: ''
description: "Blockchain | Investing | Organic | Coworking\_"
