layout_spectrum: 0.3824692356865853
typography_spectrum: 0.8760900483466685
color:
  saturation: 0.517585763707757
  brandStrength: 0.8884557662531734
  rhythmicContrast: 0.1724482304416597
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
  lightness: 0.8681929311715066
title: ''
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: "Blockchain | Investing | Organic | Coworking\_"
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/45c9fde1-3a11-48a4-bb54-8c211e7390d4.png
name: fivecloves
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8f9f2c37-6361-4b15-9bb7-52b5d45902f6.png
