layout_spectrum: 0.5491300483699888
typography_spectrum: 0.8285446304362267
color:
  saturation: 0.6565779247321188
  brandStrength: 0.6287015543784946
  rhythmicContrast: 0.08832667651586235
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
  lightness: 0.44851268199272454
logo: null
name: fivecloves
navigation:
  - name: Career
    id: de32afbe-c0e0-4d44-8cbf-3a577f522492
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/45c9fde1-3a11-48a4-bb54-8c211e7390d4.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: ''
description: Blockchain | Investing | Coworking | Organic
